receivers:
  postgresql/prod:
    endpoint: "u4oo48sg0w8g8wg0swowso08:5432"
    transport: tcp
    username: "postgres"
    password: "7bU8C8basOtOpMDsIZQPruj61jfEYGkeKwV2LoJ6mPTPDjzyqqR7IIoMPOpSvkLg"
    databases: ["postgres"]
    collection_interval: 10s
    tls:
      insecure: true

  postgresql/dev:
    endpoint: "postgresql-develop:5432"
    transport: tcp
    username: "postgres"
    password: "nYmczM6AOQNhGovgMS2Kx0L9UN0p6QotEaXe0tU2l2eOVE8G1SxGmKcXK6eXJteL"
    databases: ["postgres"]
    collection_interval: 10s
    tls:
      insecure: true

  redis/prod:
    endpoint: "wc4g00ook8ck08css8c40ksk:6379"
    password: "28Xm3EQKKPnYMtgJBC8lteIbGD8KKOl0GyTQxGLUygKl74lZDUsZszRZ9WXDGGRc"
    collection_interval: 10s

  redis/dev:
    endpoint: "redis-dev:6379"
    password: "hwIRWD2pz46Fucg3MobYx0WJ52idqD2zPfF3HQ9Vm8AP2DGw5GNUIG0yAN1u6umO"
    collection_interval: 10s

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      network:
      filesystem:
      load:
      paging:

exporters:
  otlphttp:
    endpoint: "http://openobserve-217.216.35.77.sslip.io/api/default/"
    headers:
      Authorization: "Basic aXJmYW5kaW1hcnN5YUBnbWFpbC5jb206am1XVTZFN0U1VkZxQXlVcw=="
      stream-name: "default"

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [postgresql/prod, postgresql/dev, redis/prod, redis/dev, hostmetrics]
      processors: [batch]
      exporters: [otlphttp]
